### ISSUE TITLE
how to add this template on existing project ? 

### ISSUE THREAD

**Issue by rizalashidiq97** [reduxjs/cra-template-redux#17]

**Comment by nickserv** [comment]
`npx create-react-app --template redux` then copy over your existing files and refactor to use Redux Toolkit if necessary

**Comment by markerikson** [comment]
Yeah - the point of CRA templates is that you use them when you're creating a new project.  As Nick said, you'd need to either create a new project, copy the source back and forth, and go from there, or just use this as an example for refactoring your existing project.
