### ISSUE TITLE
move some dependencies to devDependencies 

### ISSUE THREAD

**Issue by yoangau** [reduxjs/cra-template-redux#32]
After `npx create-react-app my-app --template redux-typescript` these packages should be in the devDependencies:

 `@types/jest @types/node @types/react @types/react-dom @types/react-redux react-scripts typescript @testing-library/jest-dom @testing-library/react @testing-library/user-event`

instead in the general dependencies. Tell me what you guys think!

**Comment by nickserv** [comment]
This is intentional as create-react-app's default templates only use `dependencies`. It doesn't really matter which section you use if you're not publishing a web app, CRA/webpack will only bundle imported dependencies anyway.
