### ISSUE TITLE
Update template for React 18 and React-Redux v8

### ISSUE THREAD

**Issue by markerikson** [reduxjs/cra-template-redux#52]
We need to update this template to support React 18 and React-Redux v8.  

This should include:

- Changing the template rendering setup to match React 18's `createRoot()`, per https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html and https://github.com/facebook/create-react-app/pull/12220
- Updating all dependencies to the latest
- Specifically updating `react-redux` to the latest 8.0-rc (and eventually 8.0 final, but I'd like to have the PR for the template ready before I release 8.0): https://github.com/reduxjs/react-redux/releases

Related TS template issue: https://github.com/reduxjs/cra-template-redux-typescript/issues/65

**Comment by markerikson** [comment]
As a related note: I'd actually rather like to move both the templates into this repo, and maybe have a couple other templates here too?  

The Next template already lives directly in the Next repo, at https://github.com/vercel/next.js/tree/canary/examples/with-redux .  But, we don't have any kind of an official RN template, and it'd be nice to point to one of those too.

I did talk about this some in https://github.com/reduxjs/redux/issues/4035 as well.

**Comment by souzaramon** [comment]
I would be happy to help

**Comment by souzaramon** [comment]
I'm starting at #53

**Comment by souzaramon** [comment]
Here this problem has gotten more atencion:

https://github.com/facebook/create-react-app/issues/2377

Not sure if its the best solution, but the minimal change its just set NODE_ENV, so I add the cross-env lib. I'll make some tests to see if everything is working fine, but I'll appreciate any comment in this

**Comment by markerikson** [comment]
Merged the PR.  Would you be interested in doing the TS template as well?
