### ISSUE TITLE
Post-1.0 tweaks

### ISSUE THREAD

**Issue by markerikson** [reduxjs/cra-template-redux#7]
After trying this out, a few thoughts for tweaks:

- It would be good to either show use of an inline selector with `useSelector`, or add a comment right above the `useSelector` saying you can define them inline
- I'd like to tweak the slice comment slightly and say:

```js
      // Redux Toolkit allows us write "mutating" logic in reducers. It doesn't 
      // actually mutate the state because it uses the immer library, which detects
      // changes to a "draft state" and produces a brand new immutable state
      // based off those changes
```

- We should have an example of a thunk somewhere.  Simplest example would be an "Add Async" button that sleeps for 1 second and then dispatches `increment()`.
- I want to move `store.js` into an `app` subfolder.

These changes should also be made to the TS template as well.

/cc @BenLorantfy , @lukyth

**Comment by albseb511** [comment]
Hey @markerikson 

Hey regarding the thunk example I made a PR. Would that work?

https://github.com/reduxjs/cra-template-redux/pull/8

Thanks!

**Comment by nickserv** [comment]
I think this is done

**Comment by markerikson** [comment]
Yep.
